config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :mbway_providers, :except => [:show, :destroy] do
      put :toggle_activation, :on => :member
    end
  end
  
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :payments, only: [] do
        get 'capture_mbway_payment', on: :collection
      end
    end
  end
end

app/models/decorators/payment_decorator.rb
module Decorators::PaymentDecorator
  def self.prepended(base)
    base.before_create :assign_mbway_provider
    base.belongs_to :mbway_provider
    base.scope :from_mbway, -> { joins(:payment_method).where(spree_payment_methods: { type: 'Spree::PaymentMethod::MBWay' }) }
  end

  def assign_mbway_provider
    if self.payment_method.type == 'Spree::PaymentMethod::MBWay' && Spree::MBWayProvider.active.any?
      self.mbway_provider = Spree::MBWayProvider.active.first
    end
  end

  def start_mbway_payment(description)
    if self.payment_method.type == 'Spree::PaymentMethod::MBWay'
      response = self.payment_method.send_request(self.mbway_provider.key, self.order.number, self.amount.to_f, self.mbway_mobile_number, description)
      if response && response["IdPedido"]
        self.update(mbway_request_code: response["IdPedido"])
      end
      response && response["MsgDescricao"]
    else
      nil
    end
  end

  def check_mbway_payment
    if self.payment_method.type == 'Spree::PaymentMethod::MBWay'
      response = self.payment_method.request_status(self.mbway_provider.key, self.mbway_request_code)
      response && response["EstadoPedidos"] && response["EstadoPedidos"].first["MsgDescricao"]
    else
      nil
    end
  end
end

::Spree::Payment.prepend(Decorators::PaymentDecorator)

app/models/spree/mbway_provider.rb
module Spree
  class MBWayProvider < ActiveRecord::Base
  	has_many :payments
    validates :name, :key, presence: true
    
    scope :active, -> { where(active: true) }
  end
end

app/models/spree/payment_method/mbway.rb
module Spree
  class PaymentMethod::MBWay < PaymentMethod
    def actions
      %w{capture void}
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def capture(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def void(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def source_required?
      false
    end
      
    def credit(money, credit_card, response_code, options = {})
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end


    # The following code is specific to the IfThenPay service
    API_BASE_URL = "https://www.ifthenpay.com/mbwayws/IfthenPayMBW.asmx"

    def send_request(mbway_key, order_number, order_amount, mobile_number, description)
      if self.active?
        request_params = {
          MbWayKey: mbway_key,
          canal: "03",
          referencia: order_number,
          valor: order_amount.to_s,
          nrtlm: mobile_number.gsub(/\s+/, ""),
          email: "",
          descricao: description
        }
        url = API_BASE_URL + "/SetPedidoJSON"
        # begin
          response = RestClient.post(url, request_params, {content_type: "application/x-www-form-urlencoded", accept: :json})
        # rescue => e
          # return e.response
        # end
        JSON.parse(response.body)
      else
        nil
      end
    end

    def request_status(mbway_key, request_code)
      if self.active?
        request_params = {
          MbWayKey: mbway_key,
          canal: "03",
          idspagamento: request_code
        }
        url = API_BASE_URL + "/EstadoPedidosJSON"
        # begin
          response = RestClient.post(url, request_params, {content_type: "application/x-www-form-urlencoded", accept: :json})
        # rescue => e
          # return e.response
        # end
        JSON.parse(response.body)
      else
        nil
      end
    end

  end
end

app/controllers/decorators/api/base_controller_decorator.rb
module Decorators::Api::BaseControllerDecorator
  def api_key
    request.headers["X-Spree-Token"] || params[:token] || params[:chave]
  end
end

::Spree::Api::BaseController.prepend(Decorators::Api::BaseControllerDecorator)

app/controllers/decorators/api/v1/payments_controller_decorator.rb
module Decorators::Api::V1::PaymentsControllerDecorator

  def self.prepended(base)
    base.skip_before_action :find_order, only: [:capture_mbway_payment]
    # base.before_action :find_order_and_payment, only: [:capture_mbway_payment]
  end

  def capture_mbway_payment
    find_order_and_payment
    if @payment && @order && params[:referencia] == @order.number && params[:valor].to_d == @payment.amount && params[:idpedido] == @payment.mbway_request_code
      @order.resume! if @order.state == "canceled"
      capture
      ## Send push notification
      if Spree::Config.has_preference?(:send_push_notifications) && Spree::Config[:send_push_notifications]
        NewOrderNotifyJob.perform_later(@order)
      end
      ## Handle invoice and email
      if Spree::Config.has_preference?(:automatic_invoices) && Spree::Config[:automatic_invoices]
        ## Create invoice and send paid email
        if Object.const_defined?("NewCreateInvoiceJob")
          NewCreateInvoiceJob.perform_later(@order, "paid_email")
        else
          ## Only send paid email
          @order.send_paid_email if @order.respond_to?(:send_paid_email)
        end
      else
        ## Only send paid email
        @order.send_paid_email if @order.respond_to?(:send_paid_email)
      end
      head :ok
    else
      head :not_found
    end
  end

  private

    def find_order_and_payment
      @order = Spree::Order.find_by_number(params[:referencia])
      if @order
        @payment = @order.payments.where(mbway_request_code: params[:idpedido]).last
        authorize! :read, @order, order_token
      end
    end
end

::Spree::Api::V1::PaymentsController.prepend(Decorators::Api::V1::PaymentsControllerDecorator)

app/controllers/spree/admin/mbway_providers_controller.rb
module Spree
  module Admin
    class MBWayProvidersController < ResourceController
      def index
        @search = Spree::MBWayProvider.ransack(params[:q])
        @mbway_providers = @search.result.page(params[:page])
      end

      def toggle_activation
        @success = @mbway_provider.toggle!(:active)
      end
    end
  end
end

app/helpers/spree/admin/mbway_providers_helper.rb
module Spree
  module Admin
    module MBWayProvidersHelper

      def mbway_provider_status(provider)
        provider.active? ? Spree.t(:active) : Spree.t(:inactive)
      end

      def action_to_toggle_mbway_provider_status(provider)
        provider.active? ? Spree.t(:deactivate) : Spree.t(:activate)
      end

    end
  end
end

app/views/spree/admin/mbway_providers/_form.html.erb
<div data-hook="admin_inside_mbway_provider_form" class="row">
  <div class="col-md-6">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:mbway_provider_name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :key, class: ['form-group'] do %>
      <%= f.label :key, Spree.t(:mbway_provider_key) %> <span class="required">*</span>
      <%= f.text_field :key, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :active, class: ['form-group'] do %>
      <%= f.check_box :active %>
      <%= f.label :active, Spree.t(:mbway_provider_active) %>
    <% end %>

  </div>
</div>

app/views/spree/admin/mbway_providers/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:edit_mbway_provider) %>
<% end %>

<div data-hook="admin_mbway_provider_edit_form">
  <%= form_for [:admin, @mbway_provider] do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div data-hook="admin_mbway_provider_edit_form_buttons">
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/mbway_providers/index.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t(:listing_mbway_providers) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_mbway_provider), new_admin_mbway_provider_path, :class => "btn-success", :icon => 'add', :id => 'admin_new_mbway_provider_link'%>
<% end %>

<%= paginate @mbway_providers %>

<table class='table' id="listing_mbway_providers" data-hook>
  <thead>
    <th><%= sort_link @search, :name, Spree.t(:mbway_provider_name) %></th>
    <th><%= sort_link @search, :key, Spree.t(:mbway_provider_key) %></th>
    <th><%= sort_link @search, :active, Spree.t(:mbway_provider_active) %></th>
  </thead>

  <tbody>
    <% @mbway_providers.each do |provider| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td class="align-center"><%= provider.name %></td>
        <td class="align-center"><%= provider.key %></td>
        <td class="align-center" id='active-status-<%= provider.id %>'><%= mbway_provider_status(provider) %></td>
        <td class="actions"><%= link_to action_to_toggle_mbway_provider_status(provider), toggle_activation_admin_mbway_provider_path(provider), :remote => true, :method => :put %></td>
        <td class="actions"><%= link_to_edit provider, :no_text => true, :class => 'edit' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/mbway_providers/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_mbway_provider) %>
<% end %>

<div data-hook="admin_mbway_provider_new_form">
  <%= form_for [:admin, @mbway_provider] do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div data-hook="admin_mbway_provider_new_form_buttons">
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/mbway_providers/toggle_activation.js.erb
<% if @success %>
  $('#active-status-<%= @mbway_provider.id %>').text('<%= mbway_provider_status(@mbway_provider) %>')
  $('a[href="<%= toggle_activation_admin_mbway_provider_path(@mbway_provider) %>"]').text('<%= action_to_toggle_mbway_provider_status(@mbway_provider) %>')
<% else %>
  alert('<%= @mbway_provider.errors.full_messages.to_sentence %>')
<% end %>

app/views/spree/admin/payments/source_views/_mbway.html.erb
<fieldset data-hook="mbway">
  <legend align="center"><%= Spree.t(:transaction, :scope => :mbway) %></legend>

  <div class="row">
    <div class="alpha six columns">
      <table class="table table-condensed table-bordered">
        <tr>
          <th><%= Spree.t(:amount, :scope => :mbway) %>:</th>
          <td><%= payment.display_amount.to_html %></td>
        </tr>
      </table>
    </div>
  </div>
</fieldset>

app/views/spree/checkout/payment/_mbway.html.haml
-# .well.clearfix
-#   - if (providers = Spree::MBWayProvider.active).any? 
-#     %table.table
-#       %tr
-#         %th= Spree.t(:mbway_provider_name)
-#       - providers.each do |provider| 
-#         %tr
-#           %td= provider.name